[build]
  command = "rustup install nightly --profile minimal && cargo +nightly doc --no-deps"
  environment = { RUSTDOCFLAGS= "--cfg docsrs" }
  publish = "target/doc"

[[redirects]]
  from = "/"
  to = "/tracing"
